"""
performance_review_agent.py
═══════════════════════════════════════════════════════════════════
THE ONE CONTROLLED AI AGENT in this EPMS backend.

Architecture: RAG-READY
  • Structured data comes exclusively from PostgreSQL (via SQLAlchemy).
  • A rag_context parameter is accepted to inject retrieved HR-policy
    chunks (from a vector store) when RAG is wired up later — no
    frontend or model changes needed.
  • If OPENAI_API_KEY is not configured, a rich deterministic mock
    summary is returned so the UI works out of the box.

Responsibilities:
  1. Accept employee_id
  2. Fetch employee, goals, reviews, feedback, metrics from PostgreSQL
  3. Build a structured, data-grounded HR prompt
  4. Call LLM (GPT-4o-mini) — or return mock
  5. Store result in ai_summaries table
  6. Return summary text to the caller
═══════════════════════════════════════════════════════════════════
"""

from __future__ import annotations

from sqlalchemy.orm import Session
from datetime import datetime, timezone

from app.models.employee import Employee
from app.models.goal import Goal
from app.models.review import Review, ReviewStatus
from app.models.feedback import Feedback360
from app.models.ai_summary import AISummary
from app.services.performance_service import get_metrics_by_employee
from app.config import settings

# ── LLM client (lazy-initialised) ────────────────────────────────────────────
_openai_client = None

def _get_openai():
    global _openai_client
    if _openai_client is None and _is_openai_configured():
        from openai import OpenAI
        _openai_client = OpenAI(api_key=settings.openai_api_key)
    return _openai_client


def _is_openai_configured() -> bool:
    key = settings.openai_api_key or ""
    return bool(key) and key.startswith("sk-") and "your" not in key.lower()


# ── System prompt ─────────────────────────────────────────────────────────────
_SYSTEM_PROMPT = """You are a senior HR Performance Review Agent embedded in an
Enterprise Performance Management System.

Your task: generate a concise, professional, and strictly data-driven performance
review summary for one employee.

MANDATORY RULES:
- Every statement must be grounded in the data provided. Never invent facts.
- Professional HR tone throughout.
- Structure the output with EXACTLY these Markdown sections:
  ## Overall Performance
  ## Key Strengths
  ## Areas for Improvement
  ## Goal Progress
  ## Actionable Recommendations
  ## Closing Note
- Target length: 200–250 words.
- Use bullet points inside sections where appropriate.
- End with the disclaimer line:
  *This summary was generated by the EPMS Performance Review Agent and is based
  strictly on data recorded in the system.*"""


# ── Public entry point ────────────────────────────────────────────────────────

async def run(employee_id: str, db: Session, rag_context: str = "") -> str:
    """
    Main agent entry point.

    Parameters
    ----------
    employee_id : str
    db          : SQLAlchemy session
    rag_context : optional RAG-retrieved text (HR policies, appraisal rules, etc.)
                  injected when the vector store is wired up — no code changes needed.

    Returns
    -------
    str  — Markdown-formatted performance review summary
    """
    # 1. Fetch all data from PostgreSQL
    employee = db.query(Employee).filter(Employee.id == employee_id).first()
    if not employee:
        raise ValueError(f"Employee '{employee_id}' not found")

    goals    = db.query(Goal).filter(Goal.employee_id == employee_id).all()
    reviews  = db.query(Review).filter(Review.employee_id == employee_id).all()
    feedback = db.query(Feedback360).filter(Feedback360.employee_id == employee_id).all()
    metrics_data = get_metrics_by_employee(employee_id, db)

    # 2. Build prompt
    user_prompt = _build_prompt(employee, goals, reviews, feedback,
                                metrics_data["metrics"], rag_context)

    # 3. Call LLM or mock
    if _is_openai_configured():
        summary_text = await _call_openai(user_prompt)
    else:
        summary_text = _mock_summary(employee, goals, reviews, feedback,
                                     metrics_data["metrics"])

    # 4. Persist
    record = AISummary(
        employee_id=employee_id,
        summary_text=summary_text,
        generated_at=datetime.now(timezone.utc),
    )
    db.add(record)
    db.commit()

    return summary_text


# ── Prompt builder ────────────────────────────────────────────────────────────

def _build_prompt(employee, goals, reviews, feedback, metrics: list, rag_context: str) -> str:
    # Employee header
    lines = [
        "EMPLOYEE PERFORMANCE DATA",
        "=" * 50,
        f"Name:              {employee.name}",
        f"Role:              {employee.role}",
        f"Department:        {employee.department}",
        f"Join Date:         {employee.join_date}",
        f"Performance Score: {employee.performance_score}/5",
        f"9-Box Position:    Performance={employee.nine_box_performance}, "
        f"Potential={employee.nine_box_potential}",
        "",
    ]

    # Goals
    lines.append(f"GOALS ({len(goals)} total)")
    lines.append("-" * 40)
    if goals:
        for g in goals:
            status_val = g.status.value if hasattr(g.status, "value") else g.status
            type_val   = g.type.value   if hasattr(g.type,   "value") else g.type
            lines.append(f"  • [{type_val}] {g.title}")
            lines.append(f"    Progress: {g.progress}%  |  Status: {status_val}  |  Due: {g.due_date}")
    else:
        lines.append("  No goals recorded.")
    lines.append("")

    # Completed reviews
    completed = [r for r in reviews if r.status == ReviewStatus.completed]
    lines.append(f"PERFORMANCE REVIEWS ({len(completed)} completed of {len(reviews)} total)")
    lines.append("-" * 40)
    if completed:
        for r in completed:
            type_val = r.type.value if hasattr(r.type, "value") else r.type
            strengths  = r.strengths  if isinstance(r.strengths,  list) else []
            weaknesses = r.weaknesses if isinstance(r.weaknesses, list) else []
            lines.append(f"  {type_val} Review ({r.period}) — Rating: {r.rating}/5")
            lines.append(f"    Strengths:  {', '.join(strengths)  or 'N/A'}")
            lines.append(f"    Areas:      {', '.join(weaknesses) or 'N/A'}")
            lines.append(f"    Comments:   \"{r.comments}\"")
    else:
        lines.append("  No completed reviews.")
    lines.append("")

    # 360 Feedback
    avg_fb = (sum(f.rating for f in feedback) / len(feedback)) if feedback else None
    lines.append(f"360° FEEDBACK ({len(feedback)} responses"
                 + (f", avg {avg_fb:.2f}/5" if avg_fb else "") + ")")
    lines.append("-" * 40)
    if feedback:
        for f in feedback:
            type_val = f.type.value if hasattr(f.type, "value") else f.type
            cats = f.categories or []
            cat_str = "  |  ".join(
                f"{c['name']}: {c['score']}/5" for c in cats
            ) if cats else ""
            lines.append(f"  From {f.from_name} ({type_val}): {f.rating}/5")
            lines.append(f"    \"{f.comment}\"")
            if cat_str:
                lines.append(f"    [{cat_str}]")
    else:
        lines.append("  No feedback recorded.")
    lines.append("")

    # Metrics — only those with data
    metrics_with_data = [m for m in metrics if m.get("currentValue") is not None]
    lines.append(f"PERFORMANCE METRICS ({len(metrics_with_data)} with data)")
    lines.append("-" * 40)
    for cat in ["Work Quantity", "Work Quality", "Work Efficiency",
                "Organizational", "Engagement & Development"]:
        cat_metrics = [m for m in metrics_with_data if m["category"] == cat]
        if cat_metrics:
            lines.append(f"  {cat}:")
            for m in cat_metrics:
                val = m["currentValue"]
                target = m["target"]
                status = m["status"]
                lines.append(f"    {m['name']}: {val}{m['unit']} "
                             f"(target {target}{m['unit']}, {status})")
    lines.append("")

    # RAG context slot (empty until vector store is wired up)
    if rag_context.strip():
        lines.append("RELEVANT HR POLICY CONTEXT (from knowledge base)")
        lines.append("-" * 40)
        lines.append(rag_context.strip())
        lines.append("")

    lines.append("=" * 50)
    lines.append("Generate a professional performance review summary using ONLY the data above.")

    return "\n".join(lines)


# ── OpenAI call ───────────────────────────────────────────────────────────────

async def _call_openai(user_prompt: str) -> str:
    import asyncio
    client = _get_openai()
    loop = asyncio.get_event_loop()

    def _sync_call():
        response = client.chat.completions.create(
            model=settings.openai_model or "gpt-4o-mini",
            max_tokens=700,
            temperature=0.4,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user",   "content": user_prompt},
            ],
        )
        return response.choices[0].message.content.strip()

    return await loop.run_in_executor(None, _sync_call)


# ── Deterministic mock (no API key needed) ────────────────────────────────────

def _mock_summary(employee, goals, reviews, feedback, metrics: list) -> str:
    score      = employee.performance_score
    completed  = sum(1 for g in goals if (g.status.value if hasattr(g.status, "value") else g.status) == "Completed")
    total_goals = len(goals)
    avg_fb     = (round(sum(f.rating for f in feedback) / len(feedback), 2)
                  if feedback else "N/A")
    completed_reviews = [r for r in reviews if r.status == ReviewStatus.completed]
    avg_review = (round(sum(r.rating for r in completed_reviews) / len(completed_reviews), 2)
                  if completed_reviews else "N/A")

    # Collect strengths from manager review
    mgr_review = next((r for r in completed_reviews
                       if (r.type.value if hasattr(r.type, "value") else r.type) == "Manager"), None)
    strengths_text = ""
    if mgr_review and mgr_review.strengths:
        s = mgr_review.strengths if isinstance(mgr_review.strengths, list) else []
        strengths_text = ", ".join(s[:3])
    areas_text = ""
    if mgr_review and mgr_review.weaknesses:
        w = mgr_review.weaknesses if isinstance(mgr_review.weaknesses, list) else []
        areas_text = ", ".join(w[:3])

    good_metrics  = [m for m in metrics if m.get("status") == "good"    and m.get("currentValue") is not None]
    warn_metrics  = [m for m in metrics if m.get("status") == "warning"  and m.get("currentValue") is not None]

    return f"""## Overall Performance

{employee.name} has demonstrated consistent performance as {employee.role} in the \
{employee.department} department during this review cycle, achieving an overall \
performance score of **{score}/5**. Reviews and 360° feedback collectively reflect \
a dedicated professional who delivers measurable results aligned with team objectives.

## Key Strengths

- **Demonstrated expertise**: {strengths_text or "Strong domain knowledge and execution capability."}
- **Metric performance**: {len(good_metrics)} out of {len(metrics)} tracked metrics are rated "good", \
indicating above-target delivery.
- **Peer recognition**: 360° feedback average of **{avg_fb}/5** reflects positive \
cross-functional relationships.

## Areas for Improvement

- {areas_text or "Continued focus on efficiency and communication is encouraged."}
- {len(warn_metrics)} metrics remain in the "warning" range and should be addressed in the next cycle.

## Goal Progress

{completed} of {total_goals} goals have been completed this cycle. \
Active goals show a mix of on-track and at-risk items. Prioritising at-risk goals \
before their due dates is recommended.

## Actionable Recommendations

1. Schedule bi-weekly check-ins to monitor at-risk goals.
2. Enrol in relevant L&D programmes to close identified skill gaps.
3. Leverage strengths in {strengths_text.split(',')[0] if strengths_text else 'core competencies'} \
to mentor peers.

## Closing Note

{employee.name} is a valued member of the {employee.department} team. \
With targeted focus on the improvement areas above, the next review cycle \
presents a strong opportunity for growth and advancement.

*This summary was generated by the EPMS Performance Review Agent and is based \
strictly on data recorded in the system.*"""
